### ISSUE TITLE
Source Pub/Sub module from Terraform Registry

### ISSUE THREAD

**Issue by aaron-lane** [terraform-google-modules/terraform-google-scheduled-function#12]
Currently, the Pub/Sub module is sourced directly from GitHub. Since the module has been released to the Terraform Registry, it should be sourced from there.

**Comment by anantasty** [comment]
The main.tf file is sourcing it from the terraform registry.
https://github.com/terraform-google-modules/terraform-google-scheduled-function/blob/b59cf70b5ca4e56cfcad9006d22c5e49b6fdc3dc/main.tf#L40
