### ISSUE TITLE
Release for terraform 0.12?

### ISSUE THREAD

**Issue by sindreij** [terraform-google-modules/terraform-google-scheduled-function#33]
Hi. It looks like this module is updated for terraform 0.12, but there has not been a release. Is it possible to make a release supporting 0.12?

**Comment by morgante** [comment]
0.12 support has been included since 1.0.0. 

Please review the changelog: https://github.com/terraform-google-modules/terraform-google-scheduled-function/blob/master/CHANGELOG.md#100---2019-07-30

**Comment by sindreij** [comment]
My bad. Thanks for the help :)
